[project]
name = 'Decentralized-Reality-Coherence-Maintenance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.existential-bug-bounty]
path = 'contracts/existential-bug-bounty.clar'
clarity_version = 2
epoch = 2.5

[contracts.fundamental-contradiction-resolution]
path = 'contracts/fundamental-contradiction-resolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.ontological-consistency-verification]
path = 'contracts/ontological-consistency-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-patch-deployment]
path = 'contracts/reality-patch-deployment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
